# About the Numpy Random Library
Numpy is a numerical package for Python which is fundamental for scientific computing. This library contains a multidimensional array object, matrices, masked arrays, an assortment of routines for fast operations on arrays and much more.

It has a subpackage called random, which will be the focus of this notebook.

Documentation for numpy.random can be found [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html).
***
## Contents
#### - Simple Random Data
[rand](#rand)<br>
[randn](#randn)<br>
[randint](#randint)<br>
[random](#random)<br>
[choice](#choice)<br>
#### - Permutations
[shuffle](#shuffle)<br>
[permutation](#permutation)<br>
#### - Distributions
[binomial](#binomial)<br>
[exponential](#exponential)<br>
[logistic](#logistic)<br>
[lognormal](#lognormal)<br>
[normal](#normal)<br>
[power](#power)<br>
[uniform](#uniform)<br>
***

Before we start using any numpy commands, we must first import the package.

In [1]:
import numpy as np

## Simple Random Data
These are the commands that are used to generate simple random data. These will probably be used more than the other types of commands.

### rand
Creates an array of the given shape and populates it with random samples from the "uniform" distribution over [0, 1].

In [2]:
x = np.random.rand(2, 3)
x

array([[0.24766357, 0.68847045, 0.95316564],
       [0.78838055, 0.03161478, 0.85940181]])

### randn
If parameters are specified, randn returns a sample (or samples) from the “standard normal” distribution over [0, 1].

In [3]:
x = np.random.randn(2, 3)
x

array([[ 1.02145033, -1.33294255, -0.40976268],
       [ 1.40301857,  0.06842431,  0.8603583 ]])

If no argument is provided then it returns a single float randomly sampled from the distribution.

In [4]:
x = np.random.randn()
x

0.8881330603014546

### randint
Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high).<br> 
randint has a number of optional parameters; **high**, **size** and **dtype**. <br>
If **high** is None (the default), then results are from [0, low).

In [5]:
x = np.random.randint(10)
x

3

**size** defines the shape of the output, the default is none which means only one value will be returned. <br>
**dtype** defines the data type of the result, e.g. int, int64, etc.

In [6]:
x = np.random.randint(3, 15, size = 8, dtype="int64")
x

array([ 3, 13,  4, 14, 10,  6, 10, 14], dtype=int64)

### random
Return random floats drawn from the “continuous uniform” distribution over  the half-open interval [0.0, 1.0). <br>Returns a float or an array of floats.

In [7]:
np.random.random(3)

array([0.12839615, 0.48117104, 0.74034763])

### choice
Generates a random sample from a given 1-D array. 
Its parameters are **a**, **size**, **replace** and **p**.

**size** defines the output shape. <br>
**a** accepts an int or an ndarray. If **a** is an int, choice draws it's results from 0 (inclusive) to a (exclusive). <br>

In [8]:
np.random.choice(20, 5)

array([10,  2,  0, 10, 12])

If **a** is an ndarray, choice draws its results from the elements in **a**.

In [9]:
np. random.choice((3,9,15,20,27), 5)

array([ 9,  9,  3, 20, 15])

**replace** defines whether the sample data can repeat or not. So if replace=False, then each value will be unique.

In [10]:
np.random.choice((3,9,15,20,27), 5, replace=False)

array([27, 15, 20,  3,  9])

**p** only accepts a 1-D array. It defines the probabilities associated with each entry in **a**. If undefined it assumes a uniform distribution over all entries in **a**.

In [11]:
np.random.choice((3,9,15,20,27), 5, p=[0.2, 0, 0.1, 0.2, 0.5])

array([ 3, 20, 20, 27, 20])

## Permutations
Permutating is the arranging or rearranging of members of a set into some sequence or order. 

### shuffle
Modify a sequence in-place by shuffling its contents.

In [12]:
x = [0, 1, 2, 3, 4]
np.random.shuffle(x)
x

[3, 0, 2, 1, 4]

This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

In [13]:
x = np.arange(16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.random.shuffle(x)
x

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

### permutation
Randomly permute a sequence, or return a permuted range.

This function has one parameter, **x**. If x is a multi-dimensional array, only the first index is shuffled

In [15]:
np.random.permutation([1, 2, 3, 4, 5])

array([5, 3, 2, 1, 4])

In [16]:
x = np.arange(20).reshape((4, 5))
np.random.permutation(x)

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

## Distributions
Distribution functions are used to generate random values drawn from different distribution types. 

### binomial
Draw samples from a binomial distribution.


### exponential
Draw samples from an exponential distribution.


### logistic
Draw samples from a logistic distribution.


### lognormal
Draw samples from a log-normal distribution.


### normal
Draw random samples from a normal (Gaussian) distribution.


### power
Draws samples in [0, 1] from a power distribution with positive exponent a - 1.


### uniform
Draw samples from a uniform distribution.
